language: node_js
node_js:
  - 9
cache:
  directories:
    - ~/.npm
    - node_modules
branches:
  only:
  - master
  - task4
  - task5
  - task6
script:
  - npm test -- --coverage
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls