export const SET_SEARCH_STR = 'SEARCH_STR';
export const SET_TITLE_ACTIVE = 'ACTIVE_TITLE';
export const SET_GENRE_ACTIVE = 'ACTIVE_GENRE';
export const SORT_RELEASE_DATE = 'SORT_RELEASE_DATE';
export const SORT_RATING = 'SORT_RATING';

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const FETCH_MOVIE_DETAILS_REQUEST = 'FETCH_MOVIE_DETAILS_REQUEST';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';

export const FETCH_SIMILAR_MOVIES_REQUEST = 'FETCH_SIMILAR_MOVIES_REQUEST';
export const FETCH_SIMILAR_MOVIES_SUCCESS = 'FETCH_SIMILAR_MOVIES_SUCCESS';
