export const SET_SEARCH_STR = 'SEARCH_STR';
export const SET_TITLE_ACTIVE = 'ACTIVE_TITLE';
export const SET_GENRE_ACTIVE = 'ACTIVE_GENRE';
export const SORT_RELEASE_DATE = 'SORT_RELEASE_DATE';
export const SORT_RATING = 'SORT_RATING';

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';

export const FETCH_MOVIE_DETAILS = 'FETCH_MOVIE_DETAILS';
export const FETCH_MOVIE_DETAILS_SUCCESS = 'FETCH_MOVIE_DETAILS_SUCCESS';
export const FETCH_SIMILAR_MOVIES = 'FETCH_SIMILAR_MOVIES';
export const FETCH_SIMILAR_MOVIES_SUCCESS = 'FETCH_SIMILAR_MOVIES_SUCCESS';
